
resources:
  disable_cuda: False
  
dataset:
  dataset_rootdir: './Turbots/small/resized50'
  densmaps_gt_npz: './Turbots/small/resized50/density_maps_S12_*.npz'
  # ^ shell pattern for the path to the files
  #   'density_maps_part_A_{train,test}.npz'
  num_intervals: 5

model:
  supervised: True
  # ^ True for the Supervised S-DCNet (SS-DCNet)
  #   False for the older version (unsupervised, ordinary S-DCNet)
  interval_step: 0.5
  # ^ interval size for count values
  partition_method: 2
  # ^ partition method (1 for one-linear, 2 for two-linear)
  
train:
  train_val_split: 0.9
  # ^ fraction (train_val_split) of the training set is used for training,
  #   fraction (1 - train_val_split) of the training set is used for validation
  batch_size: 1
  pretrained_ckpt: ""
  # ^ checkpoint of a pretrained model to start with
  num_epochs: 400 #default=1000
  start_epoch: 1
  # ^ manually set idx for the starting epoch (useful on restarts)
  lr_schedule:
    lr_init: 1e-3
    lr_anneal_rate: 0.99
    # ^ lr annealing rate (lr[epoch] = lr_init * lr_anneal_rate**epoch)
  optimizer:
    momentum: 0.9
    weight_decay: 1e-4
  
validation:
  batch_size: 1
  validate_ckpt_every_epochs: 400
  if_val_before_begin_train: False
  save_ckpt_every_epochs: 400
  
test:
  batch_size: 1
  trained_ckpt_for_inference: "./checkpoints/epoch_0200.pth"
  visualize: False
  imgs_for_inference_dir: "./Turbots/resized_big/train_data/tagImages/"
